/*
 * This file is generated by jOOQ.
*/
package br.com.brendowpodsclan.jokesapijooq.model.tables;


import br.com.brendowpodsclan.jokesapijooq.model.tables.tables.Author;
import br.com.brendowpodsclan.jokesapijooq.model.tables.tables.Joke;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Libraryjokes extends SchemaImpl {

    private static final long serialVersionUID = 179264008;

    /**
     * The reference instance of <code>libraryjokes</code>
     */
    public static final Libraryjokes LIBRARYJOKES = new Libraryjokes();

    /**
     * The table <code>libraryjokes.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>libraryjokes.joke</code>.
     */
    public final Joke JOKE = Joke.JOKE;

    /**
     * No further instances allowed
     */
    private Libraryjokes() {
        super("libraryjokes", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Joke.JOKE);
    }
}
