/*
 * This file is generated by jOOQ.
*/
package br.com.brendowpodsclan.jokesapijooq.model.tables;


import br.com.brendowpodsclan.jokesapijooq.model.tables.tables.Author;
import br.com.brendowpodsclan.jokesapijooq.model.tables.tables.Joke;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in libraryjokes
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>libraryjokes.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>libraryjokes.joke</code>.
     */
    public static final Joke JOKE = Joke.JOKE;
}
